### ISSUE TITLE
Idr connection via blitz

### ISSUE THREAD

**Issue by ctr26** [ome/omero-blitz#84]
I'm not entirely sure where to leave this issue, but accessing the idr using the example java code no longer works as of today. I'm assuming this is maybe covid related?

```
LoginCredentials cred = new LoginCredentials("public", "public","https://idr.openmicroscopy.org/" , 0);

Logger simpleLogger = new SimpleLogger();

Gateway gateway = new Gateway(simpleLogger);
ExperimenterData user = gateway.connect(cred);

SecurityContext ctx = new SecurityContext(user.getGroupId());
```

**Comment by joshmoore** [comment]
Thanks, @ctr26. Let's stick with your previous issue since it's an IDR issue: https://github.com/IDR/idr-py/issues/22#issuecomment-604417919
